---
# Install Docker on RHEL 7
- hosts: all
  vars:
    user: ""
    passwd: ""
    apps_state: ""
    apps: ""
    dockerurl: "" #specify your URL for Docker EE
    dockerosversion: "7" # for RHEL 7

# Install Docker EE  
  tasks:
    - name: Register an user and auto-subscribe to available content.
      redhat_subscription:
        state: present
        username: "{{ user }}"
        password: "{{ passwd }}"
        autosubscribe: true
        
    - name: Disable all RHSM repositories
      rhsm_repository:
        name: '*'
        state: disabled
    
    - name: Enable a RHSM repository RHEL 7
      rhsm_repository:
        name: rhel-7-server-rpms
    
    - name: Enable a RHSM repository RHEL 7 extras
      rhsm_repository:
        name: rhel-7-server-extras-rpms
    
    - name: Install required packages "{{ ansible_hostname }}"
      yum:
        name: "{{ item }}"
        state: present
      with_items: 
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        
    - name: Add repository
      yum_repository:
        name: docker-ee
        description: Docker EE Repos
        baseurl: "{{ dockerurl }}"
        
    - name: Install Docker EE "{{ ansible_hostname }}"
      yum:
        name: "docker-ee"
        state: present
        
    - name: enable service docker and ensure it is not masked
      systemd:
        name: docker
        enabled: yes
        masked: no
        
    - name: Make sure docker is running
      systemd: state=started name=docker
      
    - lineinfile:
        path: /etc/yum/vars/dockerurl
        line: '{{ dockerurl }}'
    
    - lineinfile:
        path: /etc/yum/vars/dockerosversion
        line: '{{ dockerosversion }}'